name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Zip the Build
      run: |
        cd ./MMES/bin/Release
        zip -r MMES-net8.0-autobuild.zip ./net8.0/ 
        cd ../../../
        mv ./MMES/bin/Release/*.zip ./ 
         
    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MMES-Autobuild.zip
        path: ./*.zip
      
   # - name: Create Release 和 Upload Release Asset
   #   uses: softprops/action-gh-release@v1
   #   if: startsWith(github.ref, 'refs/tags/')
   #   with:
        #tag_name: ${{ github.ref }}
   #     name: MMES Autobuild Version
   #     body: 自动构建版本
   #     #body_path: CHANGELOG.txt
   #     draft: false
   #     prerelease: true
   #     files: |
   #       MMES-net8.0-autobuild.zip
   #       LICENSE 
